pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '''
                    # Pull changes from GitHub
                    cd /srv/shiny-server/prod
                    git fetch origin
                    git reset --hard origin/main

                    # Add virtual environment changes
                    R -e "renv::restore()"

                    # Restart the Shiny Server service
                    sudo service shiny-server restart
                '''
            }
        }
    }
}
