# TABLES ----------------------------------------
tables_rv <-
    list(xgoals_players = list(minimum_minutes = 0,
                               minimum_shots = 0,
                               minimum_key_passes = 0,
                               date_type = "Season",
                               season_name = max(all_seasons),
                               start_date = paste0(max(all_seasons), "-01-01"),
                               end_date = paste0(max(all_seasons), "-12-31"),
                               team_id = all_teams$team_id,
                               shot_pattern = PATTERNS_OF_PLAY,
                               split_by_teams = FALSE,
                               split_by_seasons = TRUE),
         xgoals_teams = list(date_type = "Season",
                             season_name = max(all_seasons),
                             start_date = paste0(max(all_seasons), "-01-01"),
                             end_date = paste0(max(all_seasons), "-12-31"),
                             shot_pattern = PATTERNS_OF_PLAY,
                             split_by_seasons = TRUE,
                             home_only = FALSE,
                             away_only = FALSE,
                             home_adjusted = FALSE,
                             even_game_state = FALSE),
         xgoals_goalkeepers = list(minimum_minutes = 0,
                                   minimum_shots_faced = 0,
                                   date_type = "Season",
                                   season_name = max(all_seasons),
                                   start_date = paste0(max(all_seasons), "-01-01"),
                                   end_date = paste0(max(all_seasons), "-12-31"),
                                   team_id = all_teams$team_id,
                                   shot_pattern = PATTERNS_OF_PLAY,
                                   split_by_teams = FALSE,
                                   split_by_seasons = TRUE),
         xgoals_games = list(date_type = "Season",
                             season_name = max(all_seasons),
                             start_date = paste0(max(all_seasons), "-01-01"),
                             end_date = paste0(max(all_seasons), "-12-31")),
         xpass_players = list(minimum_minutes = 0,
                              minimum_passes = 0,
                              date_type = "Season",
                              season_name = max(all_seasons),
                              start_date = paste0(max(all_seasons), "-01-01"),
                              end_date = paste0(max(all_seasons), "-12-31"),
                              team_id = all_teams$team_id,
                              pass_origin_third = THIRDS_OF_FIELD,
                              split_by_teams = FALSE,
                              split_by_seasons = TRUE),
         xpass_teams = list(date_type = "Season",
                            season_name = max(all_seasons),
                            start_date = paste0(max(all_seasons), "-01-01"),
                            end_date = paste0(max(all_seasons), "-12-31"),
                            pass_origin_third = THIRDS_OF_FIELD,
                            split_by_seasons = TRUE,
                            home_only = FALSE,
                            away_only = FALSE),
         goals_added_players = list(minimum_minutes = 0,
                                    date_type = "Season",
                                    season_name = max(all_seasons),
                                    start_date = paste0(max(all_seasons), "-01-01"),
                                    end_date = paste0(max(all_seasons), "-12-31"),
                                    team_id = all_teams$team_id,
                                    split_by_teams = FALSE,
                                    split_by_seasons = TRUE),
         salaries_players = list(date_type = "Season",
                                 season_name = max(all_seasons),
                                 start_date = paste0(max(all_seasons), "-01-01"),
                                 end_date = paste0(max(all_seasons), "-12-31"),
                                 team_id = all_teams$team_id,
                                 position = MLSPA_POSITIONS),
         salaries_teams = list(season_name = max(all_seasons),
                               split_by_teams = TRUE,
                               split_by_seasons = FALSE,
                               split_by_positions = FALSE))

for (x in 1:length(tables_rv)) {
    rv_key <- names(tables_rv)[x]

    subheader <- gsub("^_", "", stri_extract_last_regex(rv_key, "_[a-z]+$"))
    header <- stri_replace_last_regex(rv_key, "_[a-z]+$", "")

    tables_rv[[rv_key]][["data_frame"]] <- tables_rv_to_df(header, subheader)
}

tables_rv <- do.call("reactiveValues", tables_rv)
