pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '''
                    # Pull changes from GitHub
                    cd /srv/shiny-server/stage
                    git pull origin main

                    # Add virtual environment changes
                    R -e "renv::restore()"
                '''
            }
        }
    }
}
