pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '''
                    # Pull changes from GitHub
					cd /srv/shiny-server/stage
					git fetch origin
                    git reset --hard origin/develop

					# Add virtual environment changes
					R -e "renv::restore()"
                '''
            }
        }
    }
}
